name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check . || true
      - name: Test
        run: pytest -q

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install
        run: |
          npm ci || npm install
      - name: Build
        run: npm run build --if-present

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . -t httpintercepter:ci
      - name: Run container
        run: |
          cid=$(docker run -d -p 8181:8181 httpintercepter:ci)
          echo "CID=$cid" >> $GITHUB_OUTPUT
          # wait for app
          for i in {1..20}; do
            if curl -fsS http://localhost:8181/healthz > /dev/null; then
              echo "App is up"; break; fi; sleep 1; done
          curl -fsS http://localhost:8181/healthz
      - name: Stop container
        if: always()
        run: |
          docker ps -q --filter ancestor=httpintercepter:ci | xargs -r docker stop
